steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -f
      - apps/api/Dockerfile
      - -t
      - us-central1-docker.pkg.dev/sentinelrag/sentinel-registry/sentinelrag-api:latest
      - .

images:
  - us-central1-docker.pkg.dev/sentinelrag/sentinel-registry/sentinelrag-api:latest
