apiVersion: v1
kind: ServiceAccount
metadata:
  name: sentinal-rag-sa
  namespace: default
  annotations:
    iam.gke.io/gcp-service-account: sentinal-rag@sentinelrag.iam.gserviceaccount.com  # ✅ Workload Identity
